// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website.Models;

namespace website.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200528192543_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("website.Models.databaseModels.AccessLevel", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LevelCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Modify")
                        .HasColumnType("bit");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.HasKey("Level");

                    b.ToTable("AccessLevels","users");
                });

            modelBuilder.Entity("website.Models.databaseModels.BoxSet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BoxSets","gamedata");
                });

            modelBuilder.Entity("website.Models.databaseModels.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Games","statistics");
                });

            modelBuilder.Entity("website.Models.databaseModels.GameDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CalculatedDifficulty")
                        .HasColumnType("float");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameEndCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameEnvironmentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameTimeLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroPositionsIncap")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("HeroTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("HouseRules")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<int>("PerceivedDifficulty")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rounds")
                        .HasColumnType("int");

                    b.Property<string>("SelectionMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserComment")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("VillainPostionsIncap")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("VillainTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("Win")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("EnvironmentName");

                    b.HasIndex("GameEnvironmentName");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("HeroTeamId");

                    b.HasIndex("VillainTeamId");

                    b.ToTable("GameDetails","statistics");
                });

            modelBuilder.Entity("website.Models.databaseModels.GameEnvironment", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BoxSetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.HasIndex("BoxSetId");

                    b.ToTable("GameEnvironments","gamedata");
                });

            modelBuilder.Entity("website.Models.databaseModels.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoxSetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrintedComplexity")
                        .HasColumnType("int");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BoxSetId");

                    b.ToTable("HeroCharacters","gamedata");
                });

            modelBuilder.Entity("website.Models.databaseModels.HeroTeam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FifthHero")
                        .HasColumnType("int");

                    b.Property<int?>("FirstHero")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthHero")
                        .HasColumnType("int");

                    b.Property<int?>("SecondHero")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdHero")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FifthHero");

                    b.HasIndex("FirstHero");

                    b.HasIndex("FourthHero");

                    b.HasIndex("SecondHero");

                    b.HasIndex("ThirdHero");

                    b.ToTable("HeroTeams","statistics");
                });

            modelBuilder.Entity("website.Models.databaseModels.LoginAttempt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttemptTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("LoginAttempts","logging");
                });

            modelBuilder.Entity("website.Models.databaseModels.PasswordHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories","logging");
                });

            modelBuilder.Entity("website.Models.databaseModels.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UserIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.ToTable("Users","users");
                });

            modelBuilder.Entity("website.Models.databaseModels.UserPermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPermissions","users");
                });

            modelBuilder.Entity("website.Models.databaseModels.Villain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoxSetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrintedDifficulty")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BoxSetId");

                    b.ToTable("VillainCharacters","gamedata");
                });

            modelBuilder.Entity("website.Models.databaseModels.VillainTeam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FifthVillain")
                        .HasColumnType("int");

                    b.Property<int?>("FirstVillain")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthVillain")
                        .HasColumnType("int");

                    b.Property<bool>("OblivAeon")
                        .HasColumnType("bit");

                    b.Property<int?>("SecondVillain")
                        .HasColumnType("int");

                    b.Property<int?>("ThirdVillain")
                        .HasColumnType("int");

                    b.Property<bool>("VillainTeamGame")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("FifthVillain");

                    b.HasIndex("FirstVillain");

                    b.HasIndex("FourthVillain");

                    b.HasIndex("SecondVillain");

                    b.HasIndex("ThirdVillain");

                    b.ToTable("VillainTeams","statistics");
                });

            modelBuilder.Entity("website.Models.databaseModels.Game", b =>
                {
                    b.HasOne("website.Models.databaseModels.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.GameDetail", b =>
                {
                    b.HasOne("website.Models.databaseModels.GameEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.GameEnvironment", null)
                        .WithMany("GameDetails")
                        .HasForeignKey("GameEnvironmentName");

                    b.HasOne("website.Models.databaseModels.Game", "Game")
                        .WithOne("GameDetails")
                        .HasForeignKey("website.Models.databaseModels.GameDetail", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.HeroTeam", "HeroTeam")
                        .WithMany()
                        .HasForeignKey("HeroTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.VillainTeam", "VillainTeam")
                        .WithMany()
                        .HasForeignKey("VillainTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.GameEnvironment", b =>
                {
                    b.HasOne("website.Models.databaseModels.BoxSet", "BoxSet")
                        .WithMany("GameEnvironments")
                        .HasForeignKey("BoxSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.Hero", b =>
                {
                    b.HasOne("website.Models.databaseModels.BoxSet", "BoxSet")
                        .WithMany("Heroes")
                        .HasForeignKey("BoxSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.HeroTeam", b =>
                {
                    b.HasOne("website.Models.databaseModels.Hero", "Fifth")
                        .WithMany("FifthPosition")
                        .HasForeignKey("FifthHero");

                    b.HasOne("website.Models.databaseModels.Hero", "First")
                        .WithMany("FirstPosition")
                        .HasForeignKey("FirstHero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.Hero", "Fourth")
                        .WithMany("FourthPosition")
                        .HasForeignKey("FourthHero");

                    b.HasOne("website.Models.databaseModels.Hero", "Second")
                        .WithMany("SecondPosition")
                        .HasForeignKey("SecondHero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.Hero", "Third")
                        .WithMany("ThirdPosition")
                        .HasForeignKey("ThirdHero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.LoginAttempt", b =>
                {
                    b.HasOne("website.Models.databaseModels.User", "User")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("website.Models.databaseModels.PasswordHistory", b =>
                {
                    b.HasOne("website.Models.databaseModels.User", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.UserPermission", b =>
                {
                    b.HasOne("website.Models.databaseModels.AccessLevel", "AccessLevel")
                        .WithMany("UserPermissions")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.User", "User")
                        .WithOne("UserPermission")
                        .HasForeignKey("website.Models.databaseModels.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.Villain", b =>
                {
                    b.HasOne("website.Models.databaseModels.BoxSet", "BoxSet")
                        .WithMany("Villains")
                        .HasForeignKey("BoxSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("website.Models.databaseModels.VillainTeam", b =>
                {
                    b.HasOne("website.Models.databaseModels.Villain", "Fifth")
                        .WithMany("FifthPosition")
                        .HasForeignKey("FifthVillain");

                    b.HasOne("website.Models.databaseModels.Villain", "First")
                        .WithMany("FirstPosition")
                        .HasForeignKey("FirstVillain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("website.Models.databaseModels.Villain", "Fourth")
                        .WithMany("FourthPosition")
                        .HasForeignKey("FourthVillain");

                    b.HasOne("website.Models.databaseModels.Villain", "Second")
                        .WithMany("SecondPosition")
                        .HasForeignKey("SecondVillain");

                    b.HasOne("website.Models.databaseModels.Villain", "Third")
                        .WithMany("ThirdPosition")
                        .HasForeignKey("ThirdVillain");
                });
#pragma warning restore 612, 618
        }
    }
}
